name = "zoom-led-room-light"
main = "src/worker.js"
compatibility_date = "2026-06-01"

workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "STATE_KV"
id = "44b7a88f011f4a7487b55c7b82ed1eb8"
preview_id = "97f844ce12684d928f33c5720c48ed16"

[vars]
POLL_SECONDS = "5"
OTA_UPSTREAM_BASE_URL = "https://cruz-evan.github.io/zoom-room-light"
ZOOM_WEBHOOK_TOPIC_FILTER = "Cronometer Board Room's Personal Meeting Room"
PICO_ROOM_ASSIGNMENTS = "{\"pico-e66430a64b5bb432\":{\"physical_room_name\":\"Aquarium\",\"zoom_meeting_room_name\":\"Cronometer Board Room's Personal Meeting Room\",\"microsoft_calendar_user_id\":\"Boardroom@cronometer.com\"},\"pico-e66430a64b2e5a35\":{\"physical_room_name\":\"Rainbow Room\",\"zoom_meeting_room_name\":\"Rainbow Room's Personal Meeting Room\",\"microsoft_calendar_user_id\":\"rainbowroom@cronometer.com\"},\"pico-e66430a64b2a8d32\":{\"physical_room_name\":\"JamRoom\",\"zoom_meeting_room_name\":\"JamRoom's Personal Meeting Room\",\"microsoft_calendar_user_id\":\"jamroom@cronometer.com\"},\"pico-e66430a64b749c36\":{\"physical_room_name\":\"IdeaFactory\",\"zoom_meeting_room_name\":\"IdeasFactory's Personal Meeting Room\",\"microsoft_calendar_user_id\":\"ideasfactory@cronometer.com\"}}"
ACTIVE_MEETING_LOOKAHEAD_MINUTES = "5"
EMPTY_ROOM_LOOKAHEAD_MINUTES = "15"
ENDING_SOON_MINUTES = "5"
SCHEDULE_END_CLEAR_GRACE_MINUTES = "5"

[triggers]
crons = ["* * * * *"]
