WIFI_SSID = "your-wifi-name"
WIFI_PASSWORD = "your-wifi-password"

# Stable board identity. Keep this stable even if the board's IP changes. Use
# "auto" to derive pico-<machine.unique_id>, or set a room name once assigned.
DEVICE_ID = "auto"

# Future Zoom Room mapping key. The relay/server maps DEVICE_ID -> ROOM_ID.
ROOM_ID = "zoom-room-a"

# Preferred deploy/ops hostname when DHCP reservations are unavailable. Use
# "auto" to derive zoom-light-<wifi-mac-suffix>, or use {mac} in a template.
# WebREPL/mpremote examples can use zoom-light-board-room-a.local.
DEVICE_HOSTNAME = "zoom-light-board-room-a"
DEVICE_HOSTNAME_PREFIX = "zoom-light"

# Board-specific LED wiring. DEVICE_ID selects the hardware entry, so the same
# secrets template can document all four boards without hardcoding pins in
# tracked firmware files.
DEVICE_HARDWARE = {
    "board-room-a": {"led_pin": 0, "led_count": 144},
    "board-room-b": {"led_pin": 2, "led_count": 144},
    "board-room-c": {"led_pin": 4, "led_count": 144},
    "board-room-d": {"led_pin": 6, "led_count": 144},
}

# Backwards-compatible single-board override if you do not use DEVICE_HARDWARE.
# LED_PIN = 0
# LED_COUNT = 144
# LED_MAX_REFRESH_FPS = 30
# LOOP_DELAY_MS = 34

# Local laptop relay example:
# STATE_URL = "http://192.168.1.42:5050/device/state"
#
# Cloud relay example:
# STATE_URL = "https://your-relay.example.com/device/state"
#
# The firmware also appends device_id automatically when STATE_URL does not
# already include it, preserving older single-device /device/state URLs.
STATE_URL = "http://YOUR_RELAY_HOST:5050/device/state"

# Optional low-privilege device token for the relay.
DEVICE_TOKEN = ""

# Optional OTA manifest URL generated by the GitHub Pages deployment workflow.
# Leave OTA_TOKEN blank for public GitHub Pages. Only set it for a protected
# OTA endpoint that expects the same low-privilege bearer style as /device/state.
OTA_MANIFEST_URL = "https://YOUR_GITHUB_USER.github.io/YOUR_REPO/manifest.json"
OTA_TOKEN = ""
# Disabled by default while USB is the recovery/update path.
OTA_ENABLED = False

# Shared key used to decrypt encrypted Wi-Fi config published to GitHub Pages.
# Generate a long random value, store the same value as GitHub secret
# OTA_CONFIG_KEY, and provision it once over USB. Do not publish this key.
OTA_CONFIG_KEY = ""
OTA_CONFIG_URL = ""
# Disabled by default because a stuck OTA config request can wedge the device.
# Re-enable only with the hardware watchdog and skip marker behavior deployed.
OTA_CONFIG_ENABLED = False

# Optional on-device telemetry over UDP. The Pico can be powered from the wall
# and still stream compact JSON logs over Wi-Fi to a laptop listener.
#
# Broadcast is convenient for bring-up:
# TELEMETRY_HOST = "255.255.255.255"
#
# A direct laptop LAN IP is usually more reliable:
# TELEMETRY_HOST = "192.168.1.42"
TELEMETRY_ENABLED = False
TELEMETRY_HOST = "255.255.255.255"
TELEMETRY_PORT = 9977
TELEMETRY_DEVICE_ID = DEVICE_ID

# Optional resource monitor sent over the same telemetry UDP channel. It emits
# resource_sample events with heap free bytes, loop timing, estimated CPU busy
# percent, over-budget loop counts, clock speed, and Pico CPU temperature.
RESOURCE_MONITOR_ENABLED = False
RESOURCE_MONITOR_SAMPLE_SECONDS = 10
RESOURCE_MONITOR_CPU_WARN_PERCENT = 80
RESOURCE_MONITOR_MIN_FREE_BYTES = 24000
RESOURCE_MONITOR_GC_COLLECT = False
RESOURCE_MONITOR_INCLUDE_TEMP = True

# Reset the board if the background network polling thread stops heartbeating.
# This recovers from stuck Wi-Fi/HTTP/OTA calls without physically power-cycling.
NETWORK_THREAD_WATCHDOG_ENABLED = True
NETWORK_THREAD_WATCHDOG_SECONDS = 30
HARDWARE_WATCHDOG_ENABLED = False
HARDWARE_WATCHDOG_TIMEOUT_MS = 8000
