WIFI_SSID = "your-wifi-name"
WIFI_PASSWORD = "your-wifi-password"

# Local laptop relay example:
# STATE_URL = "http://192.168.1.42:5050/device/state"
#
# Cloud relay example:
# STATE_URL = "https://your-relay.example.com/device/state"
STATE_URL = "http://YOUR_RELAY_HOST:5050/device/state"

# Optional low-privilege device token for the relay.
DEVICE_TOKEN = ""

# Optional OTA manifest URL generated by the GitHub Pages deployment workflow.
# Leave OTA_TOKEN blank for public GitHub Pages. Only set it for a protected
# OTA endpoint that expects the same low-privilege bearer style as /device/state.
OTA_MANIFEST_URL = "https://YOUR_GITHUB_USER.github.io/YOUR_REPO/manifest.json"
OTA_TOKEN = ""

# Optional on-device telemetry over UDP. The Pico can be powered from the wall
# and still stream compact JSON logs over Wi-Fi to a laptop listener.
#
# Broadcast is convenient for bring-up:
# TELEMETRY_HOST = "255.255.255.255"
#
# A direct laptop LAN IP is usually more reliable:
# TELEMETRY_HOST = "192.168.1.42"
TELEMETRY_ENABLED = False
TELEMETRY_HOST = "255.255.255.255"
TELEMETRY_PORT = 9977
TELEMETRY_DEVICE_ID = "zoom-led-pico"
